import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { addCertificate, createResource, getAppointments, getMyResources, getSession, updateAppointmentStatus, updateProfessional } from '../../lib/api.js'
import './DoctorDashboard.css'

export default function DoctorDashboard() {
  const session = getSession()
  const professional = session?.user.professional
  const [appointments, setAppointments] = useState([])
  const [error, setError] = useState('')
  const [post, setPost] = useState({ type: 'ARTICLE', title: '', summary: '', externalUrl: '', sourceName: '', specialties: [] })
  const [postMessage, setPostMessage] = useState('')
  const [editing, setEditing] = useState(false)
  const [profileMessage, setProfileMessage] = useState('')
  const [profile, setProfile] = useState({})
  const [certificate, setCertificate] = useState({ label: '', fileUrl: '' })
  const [certificateMessage, setCertificateMessage] = useState('')
  const [myResources, setMyResources] = useState([])

  useEffect(() => {
    getAppointments().then(({ appointments: rows }) => setAppointments(rows)).catch((loadError) => setError(loadError.message))
    getMyResources().then(({ resources }) => setMyResources(resources)).catch(() => {})
    if (professional) setProfile({ name: session.user.name, professionType: professional.professionType || professional.providerType || 'Doctor', degrees: professional.qualification?.split(',').map((value) => value.trim()).filter(Boolean) || [], specialties: professional.specialty?.split(';').map((value) => value.trim()).filter(Boolean) || [], location: professional.location || '', chamber: professional.chamber || '', phone: professional.phone || '', visitingDays: professional.visitingDays || '', visitingHours: professional.visitingHours || '', licenseAuthority: professional.licenseAuthority || '', licenseNumber: professional.licenseNumber || '', nidNumber: professional.nidNumber || '', description: professional.description || '' })
  }, [])
  async function submitPost(event) { event.preventDefault(); try { const result = await createResource(post); setMyResources((current) => [result.resource, ...current]); setPost({ type: 'ARTICLE', title: '', summary: '', externalUrl: '', sourceName: '', specialties: [] }); setPostMessage('Resource submitted for admin review.') } catch (submitError) { setPostMessage(submitError.message) } }
  async function decideAppointment(id, status) { try { await updateAppointmentStatus(id, status); setAppointments((current) => current.map((item) => item.id === id ? { ...item, status } : item)) } catch (updateError) { setError(updateError.message) } }
  async function saveProfile(event) { event.preventDefault(); try { await updateProfessional(profile); setProfileMessage('Profile saved and sent for review.'); setEditing(false) } catch (saveError) { setProfileMessage(saveError.message) } }
  async function submitCertificate(event) { event.preventDefault(); try { await addCertificate(certificate); setCertificate({ label: '', fileUrl: '' }); setCertificateMessage('Certificate path submitted for admin review.') } catch (submitError) { setCertificateMessage(submitError.message) } }
  return <div className="page doctor-dashboard"><div className="container">
    <div className="doctor-dashboard__header"><div><p className="mono">Professional dashboard</p><h1>Welcome, {session?.user.name}</h1><p>Manage your profile and patient requests from one place.</p></div><Link to="/search">Open Smart Search</Link></div>
    {professional?.verificationStatus !== 'VERIFIED' && <div className="doctor-dashboard__notice">Your profile is awaiting admin verification. You can still receive and manage requests.</div>}
    {professional?.verificationStatus === 'REJECTED' && <div className="doctor-dashboard__notice">Admin note: {professional.verificationNote || 'Please update your verification documents.'}</div>}
    <section className="doctor-dashboard__section"><div className="doctor-dashboard__section-head"><h2>Your professional profile</h2><button type="button" onClick={() => setEditing((value) => !value)}>{editing ? 'Close editor' : 'Edit profile'}</button></div>{editing ? <form className="doctor-dashboard__profile-form" onSubmit={saveProfile}>{['name', 'professionType', 'location', 'chamber', 'phone', 'visitingDays', 'visitingHours', 'licenseAuthority', 'licenseNumber', 'nidNumber'].map((field) => <input key={field} placeholder={field} value={profile[field] || ''} onChange={(event) => setProfile({ ...profile, [field]: event.target.value })} required={['name', 'professionType', 'location', 'visitingDays', 'visitingHours', 'nidNumber'].includes(field)} />)}<input placeholder="Degrees, comma separated" value={(profile.degrees || []).join(', ')} onChange={(event) => setProfile({ ...profile, degrees: event.target.value.split(',').map((value) => value.trim()).filter(Boolean) })} required /><input placeholder="Specialties, semicolon separated" value={(profile.specialties || []).join('; ')} onChange={(event) => setProfile({ ...profile, specialties: event.target.value.split(';').map((value) => value.trim()).filter(Boolean) })} required /><textarea placeholder="Professional description" rows="3" value={profile.description || ''} onChange={(event) => setProfile({ ...profile, description: event.target.value })} /><button type="submit">Save profile</button>{profileMessage && <p role="status">{profileMessage}</p>}</form> : <div className="doctor-dashboard__profile"><strong>{professional?.professionType || professional?.providerType || 'Professional'}</strong><p>{professional?.specialty}</p><p>{professional?.qualification}</p><p>{professional?.location} {professional?.chamber && ` · ${professional.chamber}`}</p><p>{professional?.visitingDays} · {professional?.visitingHours}</p><p>{professional?.phone || 'No phone added'}</p><span className="doctor-dashboard__status">{professional?.verificationStatus || 'PENDING'}</span></div>}</section>
    <section className="doctor-dashboard__section"><h2>Patient appointment requests ({appointments.length})</h2>{error && <p role="alert">{error}</p>}{appointments.map((appointment) => <article className="doctor-dashboard__appointment" key={appointment.id}><div><strong>{appointment.parent.name}</strong><p>{appointment.notes || 'Child profile'} · {new Date(appointment.scheduledAt).toLocaleString()}</p></div><div><span>{appointment.status}</span>{appointment.status === 'REQUESTED' && <><button type="button" onClick={() => decideAppointment(appointment.id, 'CONFIRMED')}>Accept</button><button type="button" onClick={() => decideAppointment(appointment.id, 'CANCELLED')}>Reject</button></>}</div></article>)}{!appointments.length && !error && <p>No appointment requests yet.</p>}</section>
    <section className="doctor-dashboard__section"><h2>My resources ({myResources.length})</h2>{myResources.map((resource) => <p key={resource.id}>{resource.title} · {resource.status}</p>)}<h3>Add resource</h3><form className="doctor-dashboard__post" onSubmit={submitPost}><select value={post.type} onChange={(event) => setPost({ ...post, type: event.target.value })}><option value="ARTICLE">Article / blog</option><option value="CASE_STUDY">Case study</option><option value="VIDEO">Video</option><option value="GUIDE">Guide</option><option value="DOWNLOADABLE">Downloadable</option></select><input placeholder="Title" value={post.title} onChange={(event) => setPost({ ...post, title: event.target.value })} required /><input placeholder="Specialties, comma separated" value={post.specialties.join(', ')} onChange={(event) => setPost({ ...post, specialties: event.target.value.split(',').map((value) => value.trim()).filter(Boolean) })} /><textarea placeholder="Summary or full article body" rows="6" value={post.summary} onChange={(event) => setPost({ ...post, summary: event.target.value })} required />{post.type !== 'GUIDE' && post.type !== 'DOWNLOADABLE' && <input placeholder="External URL (YouTube, journal, or government link)" value={post.externalUrl} onChange={(event) => setPost({ ...post, externalUrl: event.target.value })} required={post.type === 'VIDEO' || post.type === 'CASE_STUDY'} />}{post.type !== 'VIDEO' && <input placeholder="Source name" value={post.sourceName} onChange={(event) => setPost({ ...post, sourceName: event.target.value })} />}<button type="submit">Submit for review</button>{postMessage && <p role="status">{postMessage}</p>}</form></section>
    <section className="doctor-dashboard__section"><h2>Verification certificates</h2><form className="doctor-dashboard__post" onSubmit={submitCertificate}><input placeholder="Certificate label, e.g. MBBS Certificate" value={certificate.label} onChange={(event) => setCertificate({ ...certificate, label: event.target.value })} required /><input placeholder="Private Supabase Storage path" value={certificate.fileUrl} onChange={(event) => setCertificate({ ...certificate, fileUrl: event.target.value })} required /><button type="submit">Submit certificate</button>{certificateMessage && <p role="status">{certificateMessage}</p>}</form></section>
  </div></div>
}
